listen: "localhost:8000"
server_name: "YOUR FAVROUTIE SERVER NAME"
db_url: "postgresql://postgres:PASSWORD@postgres:5432/waq_prod"
static_root: "static"
default_avatar_url: "/system/accounts/avatars/default.png"
default_header_url: "/system/accounts/headers/default.png"
notfound_avatar_url: "/system/accounts/avatars/notfound.png"
notfound_header_url: "/system/accounts/headers/notfound.png"
