listen: "localhost:8000"
server_name: ""
db_url: "postgresql://postgres:PASSWORD@waq-postgres:5432/waq_dev"
static_root: "/static"
default_avatar_url: "/avatars/original/missing.png"
default_header_url: "/headers/original/missing.png"
notfound_avatar_url: "/avatars/original/missing.png"
notfound_header_url: "/headers/original/missing.png"
vapid_private_key: "5OS5_NrCP_jtMBQvYPuQyse8s3C-11YohjEeDAQR4oE"
vapid_public_key: "BEsq0u2vxWcxoVye79FQX5HU4RYwgHYJXPX_YVb6A-tBqfm2JvaiFUVNofe6SGTsvWnKIEX9dOaxLVrktQ01bXc"
webpush_subscriber: ""
