# docker-compose run waq /root/waq db:migrate
# docker-compose run waq /root/waq user:register
version: "3.9"
services:
  waq:
    image: "anqou/waq:52fc14a"
    ports:
      - "8000:8000"
    volumes:
      - ./config:/root/config
    environment:
      WAQ_CONFIG_PATH: /root/config/prod.yml
      OCAMLRUNPARAM: b
    depends_on:
      - postgres
    restart: always
  postgres:
    image: "postgres:15.2-alpine"
    environment:
      POSTGRES_DB: waq_prod
      POSTGRES_PASSWORD: PASSWORD
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
