# docker-compose run waq /root/waq db:migrate
# docker-compose run waq /root/waq user:register
version: "3.9"
services:
  waq:
    image: "anqou/waq:master"
    ports:
      - "8000:8000"
    volumes:
      - ./config:/root/config
      - ./system:/static/system
    environment:
      WAQ_CONFIG_PATH: /root/config/prod.yml
      OCAMLRUNPARAM: b
    depends_on:
      - postgres
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '10'
  postgres:
    image: "postgres:15.2-alpine"
    environment:
      POSTGRES_DB: waq_prod
      POSTGRES_PASSWORD: PASSWORD
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
