---
apiVersion: v1
kind: Service
metadata:
  name: elk
  namespace: e2e
spec:
  selector:
    app: elk
  ports:
    - port: 5314
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elk
  namespace: e2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elk
  template:
    metadata:
      labels:
        app: elk
    spec:
      containers:
        - name: elk
          image: ghcr.io/elk-zone/elk:v0.12.1
          ports:
            - name: http
              containerPort: 5314
              protocol: TCP
