---
apiVersion: v1
kind: Namespace
metadata:
  name: jaeger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.66.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: otel-http
              containerPort: 4318
              protocol: TCP
            - name: web-ui
              containerPort: 16686
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: jaeger
spec:
  ports:
    - port: 4318
      name: otel-http
    - port: 16686
      name: web-ui
  selector:
    app: jaeger
