---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: e2e
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: e2e
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-postgres-database
  namespace: e2e
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: postgres
          image: postgres
          command:
            - bash
            - -ce
            - |
              cat <<EOS | psql -U postgres -h postgres.e2e.svc
                CREATE USER mastodon CREATEDB;
                ALTER ROLE mastodon WITH PASSWORD 'password';
              EOS
              cat <<EOS | psql -U postgres -h postgres.e2e.svc
                CREATE USER waq CREATEDB;
                ALTER ROLE waq WITH PASSWORD 'password';
              EOS
              cat <<EOS | psql -U waq -h postgres.e2e.svc -d postgres
                CREATE DATABASE waq_prod;
              EOS
