---
apiVersion: batch/v1
kind: Job
metadata:
  name: reset-waq-database
  namespace: e2e
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: reset-waq-database
          image: ghcr.io/ushitora-anqou/waq:dev
          imagePullPolicy: IfNotPresent
          args:
            - db:reset
          envFrom:
            - secretRef:
                name: waq-secret-env
