---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socks5-proxy
  namespace: e2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socks5-proxy
  template:
    metadata:
      labels:
        app: socks5-proxy
    spec:
      containers:
        - name: socks5-proxy
          image: serjs/go-socks5-proxy
          ports:
            - containerPort: 1080
              name: socks
