---
apiVersion: v1
kind: Service
metadata:
  name: waq-web
  namespace: e2e
spec:
  selector:
    app: waq-web
  ports:
    - port: 8000
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waq-web
  namespace: e2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waq-web
  template:
    metadata:
      labels:
        app: waq-web
    spec:
      containers:
        - name: web
          image: ghcr.io/ushitora-anqou/waq:dev
          envFrom:
            - secretRef:
                name: waq-secret-env
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /static
              name: static
            - mountPath: /cert
              name: ca-bundle
      volumes:
        - name: static
          emptyDir: {}
        - name: ca-bundle
          configMap:
            name: ca-bundle
---
apiVersion: v1
kind: Secret
metadata:
  name: waq-secret-env
  namespace: e2e
type: Opaque
stringData:
  SERVER_NAME: "E2E_TEST_WAQ_SERVER_NAME"
  DB_URL: "postgresql://waq:password@postgres.e2e.svc:5432/waq_prod"
  STATIC_ROOT: "/static"
  VAPID_PRIVATE_KEY: "lr6m1ywLiy6OTSbp0lPKJD7RGuHcvFF7R8s4c0OrOEU"
  VAPID_PUBLIC_KEY: "BBDfkHCo603UjZYEDYSN-Yq62159oSZMDXGDBbhNaHPiAPhFnZDjP6FN1GRj5UAfHo3L4-sdyfUiFx-N50o3bF8"
  LOG_FILE_PATH: ""
  OCAMLRUNPARAM: "b"
  WAQ_GENERATE_TEST_USERS: "true"
  WAQ_DEBUG_JOB_KICK_BLOCK: "true"
  SSL_CERT_FILE: /cert/root-certs.pem
  LISTEN: "0.0.0.0:8000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waq-gateway-tls
  namespace: e2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waq-gateway-tls
  template:
    metadata:
      labels:
        app: waq-gateway-tls
    spec:
      containers:
        - name: nginx
          image: nginx:1
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
              readOnly: true
            - name: cert
              mountPath: /cert
      volumes:
        - name: nginx-conf
          configMap:
            name: waq-gateway-tls-nginx-conf
            items:
              - key: nginx.conf
                path: waq-gateway-tls.conf
        - name: cert
          secret:
            secretName: cert-waq
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: waq-gateway-tls-nginx-conf
  namespace: e2e
data:
  nginx.conf: |
    upstream backend {
      server waq-web.e2e.svc.cluster.local:8000;
    }

    server {
      listen 80;
      listen [::]:80;
      server_name waq.waq-e2e.anqou.net;
      location / { return 301 https://$host$request_uri; }
    }

    server {
      listen 443 ssl http2;
      listen [::]:443 ssl http2;
      server_name waq.waq-e2e.anqou.net;

      ssl_certificate     /cert/tls.crt;
      ssl_certificate_key /cert/tls.key;

      location / { try_files $uri @proxy; }

      location @proxy {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Proxy "";
        proxy_pass_header Server;

        proxy_pass http://backend;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: waq-gateway-tls
  namespace: e2e
spec:
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    app: waq-gateway-tls
