FROM anqou/elk:0.9.5-dev as build
FROM ubuntu:22.04
RUN apt-get update && apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*
RUN curl -s https://tunnelmole.com/sh/install-linux.sh | bash
COPY --from=build /elk/.output build
CMD [ "bash" ]
