name: Run e2e tests

on:
  pull_request:
  push:
    branches:
      - master

permissions: read-all

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - run: echo "NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}" > e2e/.env && make -C e2e start-ngrok
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: waq
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: nicknovitski/nix-develop@v1
      - run: make -C e2e create-cluster
      - run: make -C e2e test
      - run: make -C e2e logs-deploy-waq-web
        if: always()
