name: Run e2e tests

on:
  pull_request:
  push:
    branches:
      - master

permissions: read-all

jobs:
  e2e-test:
    name: e2e-test - ${{ matrix.platform }}
    runs-on: ${{ contains(matrix.platform, 'arm64') && 'ubuntu-26.04-arm' || 'ubuntu-latest' }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: waq
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: nicknovitski/nix-develop@v1
      - run: make -C e2e create-cluster
      - run: make -C e2e test
      - run: make -C e2e logs-deploy-waq-web
        if: always()
